#############################################################################
# Makefile for building: sMagick
# Generated by qmake (2.01a) (Qt 4.4.0-rc1) on: Sun Apr 27 21:53:53 2008
# Project:  sMagick.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile sMagick.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -D_DEBUG -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -march=i686 -pipe -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -march=i686 -pipe -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -I../3rdParty/libssh2/include -IGenerated -IGenerated
LINK          = g++
LFLAGS        = -Wl,--no-undefined
LIBS          = $(SUBLIBS)  -L/usr/lib/qt4 -L/devel/code/3rdParty/libssh2/src/.libs -lssh2 -lQtSql -L/usr/lib/mysql -L/usr/lib/qt4 -lQtGui -L/usr/X11R6/lib -lpng -lSM -lICE -lXrender -lXrandr -lXinerama -lfreetype -lfontconfig -lXext -lX11 -lQtNetwork -lQtCore -lz -lm -lrt -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = linux/

####### Files

SOURCES       = AES.cpp \
		AES_encryption.cpp \
		CharacterSet.cpp \
		ConnectionListModel.cpp \
		ConnectionManager.cpp \
		ConnectionManagerDlg.cpp \
		ConsoleChar.cpp \
		CreateChangeMasterPasswordDlg.cpp \
		Decoder.cpp \
		DecoderThread.cpp \
		FileTransferDlg.cpp \
		FileTransferProgressDlg.cpp \
		GroupListModel.cpp \
		main.cpp \
		MainWindowDlg.cpp \
		MasterPasswordLoginDlg.cpp \
		PixMapHash.cpp \
		PollWorkerThread.cpp \
		QPainterRenderWidget.cpp \
		QuickConnectDlg.cpp \
		RenderWidget.cpp \
		RetryLoginDlg.cpp \
		SFTP.cpp \
		SFTPThread.cpp \
		SocketSelectThread.cpp \
		SSHConnection.cpp \
		SSHWidget.cpp \
		SSHWidgetThread.cpp \
		StopWatch.cpp \
		Tabbinator.cpp \
		Terminal.cpp \
		TransferManager.cpp \
		UserPreferences.cpp \
		UserPreferencesDlg.cpp Generated/moc_ColorButton.cpp \
		Generated/moc_ConnectionAction.cpp \
		Generated/moc_ConnectionListModel.cpp \
		Generated/moc_ConnectionManagerDlg.cpp \
		Generated/moc_CreateChangeMasterPasswordDlg.cpp \
		Generated/moc_Decoder.cpp \
		Generated/moc_FileTransferProgressDlg.cpp \
		Generated/moc_GroupListModel.cpp \
		Generated/moc_MainWindowDlg.cpp \
		Generated/moc_MasterPasswordLoginDlg.cpp \
		Generated/moc_QPainterRenderWidget.cpp \
		Generated/moc_QuickConnectDlg.cpp \
		Generated/moc_SFTP.cpp \
		Generated/moc_SFTPThread.cpp \
		Generated/moc_SSHConnection.cpp \
		Generated/moc_SSHWidget.cpp \
		Generated/moc_SSHWidgetThread.cpp \
		Generated/moc_Tabbinator.cpp \
		Generated/moc_TransferManager.cpp \
		Generated/moc_UserPreferencesDlg.cpp \
		qrc_icons.cpp
OBJECTS       = linux/AES.o \
		linux/AES_encryption.o \
		linux/CharacterSet.o \
		linux/ConnectionListModel.o \
		linux/ConnectionManager.o \
		linux/ConnectionManagerDlg.o \
		linux/ConsoleChar.o \
		linux/CreateChangeMasterPasswordDlg.o \
		linux/Decoder.o \
		linux/DecoderThread.o \
		linux/FileTransferDlg.o \
		linux/FileTransferProgressDlg.o \
		linux/GroupListModel.o \
		linux/main.o \
		linux/MainWindowDlg.o \
		linux/MasterPasswordLoginDlg.o \
		linux/PixMapHash.o \
		linux/PollWorkerThread.o \
		linux/QPainterRenderWidget.o \
		linux/QuickConnectDlg.o \
		linux/RenderWidget.o \
		linux/RetryLoginDlg.o \
		linux/SFTP.o \
		linux/SFTPThread.o \
		linux/SocketSelectThread.o \
		linux/SSHConnection.o \
		linux/SSHWidget.o \
		linux/SSHWidgetThread.o \
		linux/StopWatch.o \
		linux/Tabbinator.o \
		linux/Terminal.o \
		linux/TransferManager.o \
		linux/UserPreferences.o \
		linux/UserPreferencesDlg.o \
		linux/moc_ColorButton.o \
		linux/moc_ConnectionAction.o \
		linux/moc_ConnectionListModel.o \
		linux/moc_ConnectionManagerDlg.o \
		linux/moc_CreateChangeMasterPasswordDlg.o \
		linux/moc_Decoder.o \
		linux/moc_FileTransferProgressDlg.o \
		linux/moc_GroupListModel.o \
		linux/moc_MainWindowDlg.o \
		linux/moc_MasterPasswordLoginDlg.o \
		linux/moc_QPainterRenderWidget.o \
		linux/moc_QuickConnectDlg.o \
		linux/moc_SFTP.o \
		linux/moc_SFTPThread.o \
		linux/moc_SSHConnection.o \
		linux/moc_SSHWidget.o \
		linux/moc_SSHWidgetThread.o \
		linux/moc_Tabbinator.o \
		linux/moc_TransferManager.o \
		linux/moc_UserPreferencesDlg.o \
		linux/qrc_icons.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		sMagick.pro
QMAKE_TARGET  = sMagick
DESTDIR       = 
TARGET        = sMagick

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): Generated/ui_ConnectionManager.h Generated/ui_CreateChangeMasterPassword.h Generated/ui_FileTransfer.h Generated/ui_FileTransferProgress.h Generated/ui_MainWindow.h Generated/ui_MasterPasswordLogin.h Generated/ui_QuickConnect.h Generated/ui_RetryLogin.h Generated/ui_UserPreferences.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: sMagick.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/libQtSql.prl \
		/usr/lib/qt4/libQtCore.prl \
		/usr/lib/qt4/libQtGui.prl \
		/usr/lib/qt4/libQtNetwork.prl
	$(QMAKE) -unix -o Makefile sMagick.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/qt4/libQtSql.prl:
/usr/lib/qt4/libQtCore.prl:
/usr/lib/qt4/libQtGui.prl:
/usr/lib/qt4/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile sMagick.pro

dist: 
	@$(CHK_DIR_EXISTS) linux/sMagick1.0.0 || $(MKDIR) linux/sMagick1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) linux/sMagick1.0.0/ && $(COPY_FILE) --parents AES.h AES_encryption.h CharacterSet.h ColorButton.h ConnectionAction.h ConnectionListModel.h ConnectionManager.h ConnectionManagerDlg.h ConsoleChar.h CreateChangeMasterPasswordDlg.h DataTypes.h Decoder.h DecoderThread.h FileTransferDlg.h FileTransferProgressDlg.h GroupListModel.h MainWindowDlg.h MasterPasswordLoginDlg.h PixMapHash.h PollWorkerThread.h QPainterRenderWidget.h QuickConnectDlg.h RenderWidget.h RetryLoginDlg.h SFTP.h SFTPThread.h SocketSelectThread.h SSHConnection.h SSHWidget.h SSHWidgetThread.h StopWatch.h Tabbinator.h Terminal.h TransferManager.h UserPreferences.h UserPreferencesDlg.h linux/sMagick1.0.0/ && $(COPY_FILE) --parents icons.qrc linux/sMagick1.0.0/ && $(COPY_FILE) --parents AES.cpp AES_encryption.cpp CharacterSet.cpp ConnectionListModel.cpp ConnectionManager.cpp ConnectionManagerDlg.cpp ConsoleChar.cpp CreateChangeMasterPasswordDlg.cpp Decoder.cpp DecoderThread.cpp FileTransferDlg.cpp FileTransferProgressDlg.cpp GroupListModel.cpp main.cpp MainWindowDlg.cpp MasterPasswordLoginDlg.cpp PixMapHash.cpp PollWorkerThread.cpp QPainterRenderWidget.cpp QuickConnectDlg.cpp RenderWidget.cpp RetryLoginDlg.cpp SFTP.cpp SFTPThread.cpp SocketSelectThread.cpp SSHConnection.cpp SSHWidget.cpp SSHWidgetThread.cpp StopWatch.cpp Tabbinator.cpp Terminal.cpp TransferManager.cpp UserPreferences.cpp UserPreferencesDlg.cpp linux/sMagick1.0.0/ && $(COPY_FILE) --parents Ui/ConnectionManager.ui Ui/CreateChangeMasterPassword.ui Ui/FileTransfer.ui Ui/FileTransferProgress.ui Ui/MainWindow.ui Ui/MasterPasswordLogin.ui Ui/QuickConnect.ui Ui/RetryLogin.ui Ui/UserPreferences.ui linux/sMagick1.0.0/ && (cd `dirname linux/sMagick1.0.0` && $(TAR) sMagick1.0.0.tar sMagick1.0.0 && $(COMPRESS) sMagick1.0.0.tar) && $(MOVE) `dirname linux/sMagick1.0.0`/sMagick1.0.0.tar.gz . && $(DEL_FILE) -r linux/sMagick1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: Generated/moc_ColorButton.cpp Generated/moc_ConnectionAction.cpp Generated/moc_ConnectionListModel.cpp Generated/moc_ConnectionManagerDlg.cpp Generated/moc_CreateChangeMasterPasswordDlg.cpp Generated/moc_Decoder.cpp Generated/moc_FileTransferProgressDlg.cpp Generated/moc_GroupListModel.cpp Generated/moc_MainWindowDlg.cpp Generated/moc_MasterPasswordLoginDlg.cpp Generated/moc_QPainterRenderWidget.cpp Generated/moc_QuickConnectDlg.cpp Generated/moc_SFTP.cpp Generated/moc_SFTPThread.cpp Generated/moc_SSHConnection.cpp Generated/moc_SSHWidget.cpp Generated/moc_SSHWidgetThread.cpp Generated/moc_Tabbinator.cpp Generated/moc_TransferManager.cpp Generated/moc_UserPreferencesDlg.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) Generated/moc_ColorButton.cpp Generated/moc_ConnectionAction.cpp Generated/moc_ConnectionListModel.cpp Generated/moc_ConnectionManagerDlg.cpp Generated/moc_CreateChangeMasterPasswordDlg.cpp Generated/moc_Decoder.cpp Generated/moc_FileTransferProgressDlg.cpp Generated/moc_GroupListModel.cpp Generated/moc_MainWindowDlg.cpp Generated/moc_MasterPasswordLoginDlg.cpp Generated/moc_QPainterRenderWidget.cpp Generated/moc_QuickConnectDlg.cpp Generated/moc_SFTP.cpp Generated/moc_SFTPThread.cpp Generated/moc_SSHConnection.cpp Generated/moc_SSHWidget.cpp Generated/moc_SSHWidgetThread.cpp Generated/moc_Tabbinator.cpp Generated/moc_TransferManager.cpp Generated/moc_UserPreferencesDlg.cpp
Generated/moc_ColorButton.cpp: ColorButton.h
	/usr/bin/moc $(DEFINES) $(INCPATH) ColorButton.h -o Generated/moc_ColorButton.cpp

Generated/moc_ConnectionAction.cpp: DataTypes.h \
		ConnectionAction.h
	/usr/bin/moc $(DEFINES) $(INCPATH) ConnectionAction.h -o Generated/moc_ConnectionAction.cpp

Generated/moc_ConnectionListModel.cpp: DataTypes.h \
		ConnectionListModel.h
	/usr/bin/moc $(DEFINES) $(INCPATH) ConnectionListModel.h -o Generated/moc_ConnectionListModel.cpp

Generated/moc_ConnectionManagerDlg.cpp: Generated/ui_ConnectionManager.h \
		ConnectionManager.h \
		AES_encryption.h \
		AES.h \
		DataTypes.h \
		ConnectionListModel.h \
		MainWindowDlg.h \
		Generated/ui_MainWindow.h \
		Tabbinator.h \
		UserPreferences.h \
		ConsoleChar.h \
		PixMapHash.h \
		TransferManager.h \
		SFTPThread.h \
		SFTP.h \
		SSHConnection.h \
		FileTransferProgressDlg.h \
		Generated/ui_FileTransferProgress.h \
		GroupListModel.h \
		ConnectionManagerDlg.h
	/usr/bin/moc $(DEFINES) $(INCPATH) ConnectionManagerDlg.h -o Generated/moc_ConnectionManagerDlg.cpp

Generated/moc_CreateChangeMasterPasswordDlg.cpp: Generated/ui_CreateChangeMasterPassword.h \
		CreateChangeMasterPasswordDlg.h
	/usr/bin/moc $(DEFINES) $(INCPATH) CreateChangeMasterPasswordDlg.h -o Generated/moc_CreateChangeMasterPasswordDlg.cpp

Generated/moc_Decoder.cpp: DataTypes.h \
		ConsoleChar.h \
		Terminal.h \
		CharacterSet.h \
		Decoder.h
	/usr/bin/moc $(DEFINES) $(INCPATH) Decoder.h -o Generated/moc_Decoder.cpp

Generated/moc_FileTransferProgressDlg.cpp: Generated/ui_FileTransferProgress.h \
		FileTransferProgressDlg.h
	/usr/bin/moc $(DEFINES) $(INCPATH) FileTransferProgressDlg.h -o Generated/moc_FileTransferProgressDlg.cpp

Generated/moc_GroupListModel.cpp: DataTypes.h \
		GroupListModel.h
	/usr/bin/moc $(DEFINES) $(INCPATH) GroupListModel.h -o Generated/moc_GroupListModel.cpp

Generated/moc_MainWindowDlg.cpp: Generated/ui_MainWindow.h \
		ConnectionManager.h \
		AES_encryption.h \
		AES.h \
		DataTypes.h \
		Tabbinator.h \
		UserPreferences.h \
		ConsoleChar.h \
		PixMapHash.h \
		TransferManager.h \
		SFTPThread.h \
		SFTP.h \
		SSHConnection.h \
		FileTransferProgressDlg.h \
		Generated/ui_FileTransferProgress.h \
		MainWindowDlg.h
	/usr/bin/moc $(DEFINES) $(INCPATH) MainWindowDlg.h -o Generated/moc_MainWindowDlg.cpp

Generated/moc_MasterPasswordLoginDlg.cpp: Generated/ui_MasterPasswordLogin.h \
		MasterPasswordLoginDlg.h
	/usr/bin/moc $(DEFINES) $(INCPATH) MasterPasswordLoginDlg.h -o Generated/moc_MasterPasswordLoginDlg.cpp

Generated/moc_QPainterRenderWidget.cpp: RenderWidget.h \
		DataTypes.h \
		ConsoleChar.h \
		UserPreferences.h \
		PixMapHash.h \
		QPainterRenderWidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) QPainterRenderWidget.h -o Generated/moc_QPainterRenderWidget.cpp

Generated/moc_QuickConnectDlg.cpp: Generated/ui_QuickConnect.h \
		ConnectionManager.h \
		AES_encryption.h \
		AES.h \
		DataTypes.h \
		QuickConnectDlg.h
	/usr/bin/moc $(DEFINES) $(INCPATH) QuickConnectDlg.h -o Generated/moc_QuickConnectDlg.cpp

Generated/moc_SFTP.cpp: SSHConnection.h \
		DataTypes.h \
		SFTP.h
	/usr/bin/moc $(DEFINES) $(INCPATH) SFTP.h -o Generated/moc_SFTP.cpp

Generated/moc_SFTPThread.cpp: SFTP.h \
		SSHConnection.h \
		DataTypes.h \
		SFTPThread.h
	/usr/bin/moc $(DEFINES) $(INCPATH) SFTPThread.h -o Generated/moc_SFTPThread.cpp

Generated/moc_SSHConnection.cpp: DataTypes.h \
		SSHConnection.h
	/usr/bin/moc $(DEFINES) $(INCPATH) SSHConnection.h -o Generated/moc_SSHConnection.cpp

Generated/moc_SSHWidget.cpp: DataTypes.h \
		SSHWidgetThread.h \
		ConsoleChar.h \
		QPainterRenderWidget.h \
		RenderWidget.h \
		UserPreferences.h \
		PixMapHash.h \
		SSHWidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) SSHWidget.h -o Generated/moc_SSHWidget.cpp

Generated/moc_SSHWidgetThread.cpp: DataTypes.h \
		ConsoleChar.h \
		SSHWidgetThread.h
	/usr/bin/moc $(DEFINES) $(INCPATH) SSHWidgetThread.h -o Generated/moc_SSHWidgetThread.cpp

Generated/moc_Tabbinator.cpp: DataTypes.h \
		UserPreferences.h \
		ConsoleChar.h \
		PixMapHash.h \
		Tabbinator.h
	/usr/bin/moc $(DEFINES) $(INCPATH) Tabbinator.h -o Generated/moc_Tabbinator.cpp

Generated/moc_TransferManager.cpp: DataTypes.h \
		SFTPThread.h \
		SFTP.h \
		SSHConnection.h \
		TransferManager.h
	/usr/bin/moc $(DEFINES) $(INCPATH) TransferManager.h -o Generated/moc_TransferManager.cpp

Generated/moc_UserPreferencesDlg.cpp: Generated/ui_UserPreferences.h \
		ColorButton.h \
		MainWindowDlg.h \
		Generated/ui_MainWindow.h \
		ConnectionManager.h \
		AES_encryption.h \
		AES.h \
		DataTypes.h \
		Tabbinator.h \
		UserPreferences.h \
		ConsoleChar.h \
		PixMapHash.h \
		TransferManager.h \
		SFTPThread.h \
		SFTP.h \
		SSHConnection.h \
		FileTransferProgressDlg.h \
		Generated/ui_FileTransferProgress.h \
		UserPreferencesDlg.h
	/usr/bin/moc $(DEFINES) $(INCPATH) UserPreferencesDlg.h -o Generated/moc_UserPreferencesDlg.cpp

compiler_rcc_make_all: qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp
qrc_icons.cpp: icons.qrc \
		icons/link_connected.png \
		icons/page_copy.png \
		icons/page_paste.png \
		icons/link_go.png \
		icons/link_warning.png \
		icons/delete.png \
		icons/pencil_go.png \
		icons/add.png \
		icons/arrow_right.png \
		icons/link_disconnected.png \
		icons/link_error.png \
		icons/page_add.png \
		icons/arrow_left.png \
		icons/folder_add.png \
		icons/icon.svg \
		icons/cross.png \
		icons/bell.png
	/usr/bin/rcc -name icons icons.qrc -o qrc_icons.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: Generated/ui_ConnectionManager.h Generated/ui_CreateChangeMasterPassword.h Generated/ui_FileTransfer.h Generated/ui_FileTransferProgress.h Generated/ui_MainWindow.h Generated/ui_MasterPasswordLogin.h Generated/ui_QuickConnect.h Generated/ui_RetryLogin.h Generated/ui_UserPreferences.h
compiler_uic_clean:
	-$(DEL_FILE) Generated/ui_ConnectionManager.h Generated/ui_CreateChangeMasterPassword.h Generated/ui_FileTransfer.h Generated/ui_FileTransferProgress.h Generated/ui_MainWindow.h Generated/ui_MasterPasswordLogin.h Generated/ui_QuickConnect.h Generated/ui_RetryLogin.h Generated/ui_UserPreferences.h
Generated/ui_ConnectionManager.h: Ui/ConnectionManager.ui
	/usr/bin/uic Ui/ConnectionManager.ui -o Generated/ui_ConnectionManager.h

Generated/ui_CreateChangeMasterPassword.h: Ui/CreateChangeMasterPassword.ui
	/usr/bin/uic Ui/CreateChangeMasterPassword.ui -o Generated/ui_CreateChangeMasterPassword.h

Generated/ui_FileTransfer.h: Ui/FileTransfer.ui
	/usr/bin/uic Ui/FileTransfer.ui -o Generated/ui_FileTransfer.h

Generated/ui_FileTransferProgress.h: Ui/FileTransferProgress.ui
	/usr/bin/uic Ui/FileTransferProgress.ui -o Generated/ui_FileTransferProgress.h

Generated/ui_MainWindow.h: Ui/MainWindow.ui
	/usr/bin/uic Ui/MainWindow.ui -o Generated/ui_MainWindow.h

Generated/ui_MasterPasswordLogin.h: Ui/MasterPasswordLogin.ui
	/usr/bin/uic Ui/MasterPasswordLogin.ui -o Generated/ui_MasterPasswordLogin.h

Generated/ui_QuickConnect.h: Ui/QuickConnect.ui
	/usr/bin/uic Ui/QuickConnect.ui -o Generated/ui_QuickConnect.h

Generated/ui_RetryLogin.h: Ui/RetryLogin.ui
	/usr/bin/uic Ui/RetryLogin.ui -o Generated/ui_RetryLogin.h

Generated/ui_UserPreferences.h: Ui/UserPreferences.ui \
		ColorButton.h
	/usr/bin/uic Ui/UserPreferences.ui -o Generated/ui_UserPreferences.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

linux/AES.o: AES.cpp AES.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/AES.o AES.cpp

linux/AES_encryption.o: AES_encryption.cpp AES_encryption.h \
		AES.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/AES_encryption.o AES_encryption.cpp

linux/CharacterSet.o: CharacterSet.cpp CharacterSet.h \
		DataTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/CharacterSet.o CharacterSet.cpp

linux/ConnectionListModel.o: ConnectionListModel.cpp ConnectionListModel.h \
		DataTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/ConnectionListModel.o ConnectionListModel.cpp

linux/ConnectionManager.o: ConnectionManager.cpp ConnectionManager.h \
		AES_encryption.h \
		AES.h \
		DataTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/ConnectionManager.o ConnectionManager.cpp

linux/ConnectionManagerDlg.o: ConnectionManagerDlg.cpp MainWindowDlg.h \
		Generated/ui_MainWindow.h \
		ConnectionManager.h \
		AES_encryption.h \
		AES.h \
		DataTypes.h \
		Tabbinator.h \
		UserPreferences.h \
		ConsoleChar.h \
		PixMapHash.h \
		TransferManager.h \
		SFTPThread.h \
		SFTP.h \
		SSHConnection.h \
		FileTransferProgressDlg.h \
		Generated/ui_FileTransferProgress.h \
		ConnectionManagerDlg.h \
		Generated/ui_ConnectionManager.h \
		ConnectionListModel.h \
		GroupListModel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/ConnectionManagerDlg.o ConnectionManagerDlg.cpp

linux/ConsoleChar.o: ConsoleChar.cpp ConsoleChar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/ConsoleChar.o ConsoleChar.cpp

linux/CreateChangeMasterPasswordDlg.o: CreateChangeMasterPasswordDlg.cpp CreateChangeMasterPasswordDlg.h \
		Generated/ui_CreateChangeMasterPassword.h \
		ConnectionManager.h \
		AES_encryption.h \
		AES.h \
		DataTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/CreateChangeMasterPasswordDlg.o CreateChangeMasterPasswordDlg.cpp

linux/Decoder.o: Decoder.cpp Decoder.h \
		DataTypes.h \
		ConsoleChar.h \
		Terminal.h \
		CharacterSet.h \
		SSHConnection.h \
		StopWatch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/Decoder.o Decoder.cpp

linux/DecoderThread.o: DecoderThread.cpp DecoderThread.h \
		ConsoleChar.h \
		Decoder.h \
		DataTypes.h \
		Terminal.h \
		CharacterSet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/DecoderThread.o DecoderThread.cpp

linux/FileTransferDlg.o: FileTransferDlg.cpp FileTransferDlg.h \
		DataTypes.h \
		Generated/ui_FileTransfer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/FileTransferDlg.o FileTransferDlg.cpp

linux/FileTransferProgressDlg.o: FileTransferProgressDlg.cpp FileTransferProgressDlg.h \
		Generated/ui_FileTransferProgress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/FileTransferProgressDlg.o FileTransferProgressDlg.cpp

linux/GroupListModel.o: GroupListModel.cpp GroupListModel.h \
		DataTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/GroupListModel.o GroupListModel.cpp

linux/main.o: main.cpp AES_encryption.h \
		AES.h \
		CreateChangeMasterPasswordDlg.h \
		Generated/ui_CreateChangeMasterPassword.h \
		MasterPasswordLoginDlg.h \
		Generated/ui_MasterPasswordLogin.h \
		ConnectionManager.h \
		DataTypes.h \
		MainWindowDlg.h \
		Generated/ui_MainWindow.h \
		Tabbinator.h \
		UserPreferences.h \
		ConsoleChar.h \
		PixMapHash.h \
		TransferManager.h \
		SFTPThread.h \
		SFTP.h \
		SSHConnection.h \
		FileTransferProgressDlg.h \
		Generated/ui_FileTransferProgress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/main.o main.cpp

linux/MainWindowDlg.o: MainWindowDlg.cpp MainWindowDlg.h \
		Generated/ui_MainWindow.h \
		ConnectionManager.h \
		AES_encryption.h \
		AES.h \
		DataTypes.h \
		Tabbinator.h \
		UserPreferences.h \
		ConsoleChar.h \
		PixMapHash.h \
		TransferManager.h \
		SFTPThread.h \
		SFTP.h \
		SSHConnection.h \
		FileTransferProgressDlg.h \
		Generated/ui_FileTransferProgress.h \
		CreateChangeMasterPasswordDlg.h \
		Generated/ui_CreateChangeMasterPassword.h \
		ConnectionManagerDlg.h \
		Generated/ui_ConnectionManager.h \
		ConnectionListModel.h \
		GroupListModel.h \
		ConnectionAction.h \
		QuickConnectDlg.h \
		Generated/ui_QuickConnect.h \
		SSHWidget.h \
		SSHWidgetThread.h \
		QPainterRenderWidget.h \
		RenderWidget.h \
		UserPreferencesDlg.h \
		Generated/ui_UserPreferences.h \
		ColorButton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/MainWindowDlg.o MainWindowDlg.cpp

linux/MasterPasswordLoginDlg.o: MasterPasswordLoginDlg.cpp MasterPasswordLoginDlg.h \
		Generated/ui_MasterPasswordLogin.h \
		ConnectionManager.h \
		AES_encryption.h \
		AES.h \
		DataTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/MasterPasswordLoginDlg.o MasterPasswordLoginDlg.cpp

linux/PixMapHash.o: PixMapHash.cpp PixMapHash.h \
		ConsoleChar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/PixMapHash.o PixMapHash.cpp

linux/PollWorkerThread.o: PollWorkerThread.cpp PollWorkerThread.h \
		SSHConnection.h \
		DataTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/PollWorkerThread.o PollWorkerThread.cpp

linux/QPainterRenderWidget.o: QPainterRenderWidget.cpp QPainterRenderWidget.h \
		RenderWidget.h \
		DataTypes.h \
		ConsoleChar.h \
		UserPreferences.h \
		PixMapHash.h \
		StopWatch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/QPainterRenderWidget.o QPainterRenderWidget.cpp

linux/QuickConnectDlg.o: QuickConnectDlg.cpp QuickConnectDlg.h \
		Generated/ui_QuickConnect.h \
		ConnectionManager.h \
		AES_encryption.h \
		AES.h \
		DataTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/QuickConnectDlg.o QuickConnectDlg.cpp

linux/RenderWidget.o: RenderWidget.cpp RenderWidget.h \
		DataTypes.h \
		ConsoleChar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/RenderWidget.o RenderWidget.cpp

linux/RetryLoginDlg.o: RetryLoginDlg.cpp RetryLoginDlg.h \
		Generated/ui_RetryLogin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/RetryLoginDlg.o RetryLoginDlg.cpp

linux/SFTP.o: SFTP.cpp SFTP.h \
		SSHConnection.h \
		DataTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/SFTP.o SFTP.cpp

linux/SFTPThread.o: SFTPThread.cpp SFTPThread.h \
		SFTP.h \
		SSHConnection.h \
		DataTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/SFTPThread.o SFTPThread.cpp

linux/SocketSelectThread.o: SocketSelectThread.cpp SocketSelectThread.h \
		SSHConnection.h \
		DataTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/SocketSelectThread.o SocketSelectThread.cpp

linux/SSHConnection.o: SSHConnection.cpp SSHConnection.h \
		DataTypes.h \
		PollWorkerThread.h \
		DecoderThread.h \
		ConsoleChar.h \
		SocketSelectThread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/SSHConnection.o SSHConnection.cpp

linux/SSHWidget.o: SSHWidget.cpp SSHWidget.h \
		DataTypes.h \
		SSHWidgetThread.h \
		ConsoleChar.h \
		QPainterRenderWidget.h \
		RenderWidget.h \
		UserPreferences.h \
		PixMapHash.h \
		FileTransferDlg.h \
		Generated/ui_FileTransfer.h \
		RetryLoginDlg.h \
		Generated/ui_RetryLogin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/SSHWidget.o SSHWidget.cpp

linux/SSHWidgetThread.o: SSHWidgetThread.cpp SSHWidgetThread.h \
		DataTypes.h \
		ConsoleChar.h \
		SSHWidget.h \
		QPainterRenderWidget.h \
		RenderWidget.h \
		UserPreferences.h \
		PixMapHash.h \
		SSHConnection.h \
		DecoderThread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/SSHWidgetThread.o SSHWidgetThread.cpp

linux/StopWatch.o: StopWatch.cpp StopWatch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/StopWatch.o StopWatch.cpp

linux/Tabbinator.o: Tabbinator.cpp Tabbinator.h \
		DataTypes.h \
		UserPreferences.h \
		ConsoleChar.h \
		PixMapHash.h \
		ConnectionManager.h \
		AES_encryption.h \
		AES.h \
		SSHWidget.h \
		SSHWidgetThread.h \
		QPainterRenderWidget.h \
		RenderWidget.h \
		MainWindowDlg.h \
		Generated/ui_MainWindow.h \
		TransferManager.h \
		SFTPThread.h \
		SFTP.h \
		SSHConnection.h \
		FileTransferProgressDlg.h \
		Generated/ui_FileTransferProgress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/Tabbinator.o Tabbinator.cpp

linux/Terminal.o: Terminal.cpp Terminal.h \
		CharacterSet.h \
		DataTypes.h \
		ConsoleChar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/Terminal.o Terminal.cpp

linux/TransferManager.o: TransferManager.cpp TransferManager.h \
		DataTypes.h \
		SFTPThread.h \
		SFTP.h \
		SSHConnection.h \
		FileTransferProgressDlg.h \
		Generated/ui_FileTransferProgress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/TransferManager.o TransferManager.cpp

linux/UserPreferences.o: UserPreferences.cpp UserPreferences.h \
		ConsoleChar.h \
		PixMapHash.h \
		DataTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/UserPreferences.o UserPreferences.cpp

linux/UserPreferencesDlg.o: UserPreferencesDlg.cpp UserPreferencesDlg.h \
		Generated/ui_UserPreferences.h \
		ColorButton.h \
		MainWindowDlg.h \
		Generated/ui_MainWindow.h \
		ConnectionManager.h \
		AES_encryption.h \
		AES.h \
		DataTypes.h \
		Tabbinator.h \
		UserPreferences.h \
		ConsoleChar.h \
		PixMapHash.h \
		TransferManager.h \
		SFTPThread.h \
		SFTP.h \
		SSHConnection.h \
		FileTransferProgressDlg.h \
		Generated/ui_FileTransferProgress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/UserPreferencesDlg.o UserPreferencesDlg.cpp

linux/moc_ColorButton.o: Generated/moc_ColorButton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/moc_ColorButton.o Generated/moc_ColorButton.cpp

linux/moc_ConnectionAction.o: Generated/moc_ConnectionAction.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/moc_ConnectionAction.o Generated/moc_ConnectionAction.cpp

linux/moc_ConnectionListModel.o: Generated/moc_ConnectionListModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/moc_ConnectionListModel.o Generated/moc_ConnectionListModel.cpp

linux/moc_ConnectionManagerDlg.o: Generated/moc_ConnectionManagerDlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/moc_ConnectionManagerDlg.o Generated/moc_ConnectionManagerDlg.cpp

linux/moc_CreateChangeMasterPasswordDlg.o: Generated/moc_CreateChangeMasterPasswordDlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/moc_CreateChangeMasterPasswordDlg.o Generated/moc_CreateChangeMasterPasswordDlg.cpp

linux/moc_Decoder.o: Generated/moc_Decoder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/moc_Decoder.o Generated/moc_Decoder.cpp

linux/moc_FileTransferProgressDlg.o: Generated/moc_FileTransferProgressDlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/moc_FileTransferProgressDlg.o Generated/moc_FileTransferProgressDlg.cpp

linux/moc_GroupListModel.o: Generated/moc_GroupListModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/moc_GroupListModel.o Generated/moc_GroupListModel.cpp

linux/moc_MainWindowDlg.o: Generated/moc_MainWindowDlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/moc_MainWindowDlg.o Generated/moc_MainWindowDlg.cpp

linux/moc_MasterPasswordLoginDlg.o: Generated/moc_MasterPasswordLoginDlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/moc_MasterPasswordLoginDlg.o Generated/moc_MasterPasswordLoginDlg.cpp

linux/moc_QPainterRenderWidget.o: Generated/moc_QPainterRenderWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/moc_QPainterRenderWidget.o Generated/moc_QPainterRenderWidget.cpp

linux/moc_QuickConnectDlg.o: Generated/moc_QuickConnectDlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/moc_QuickConnectDlg.o Generated/moc_QuickConnectDlg.cpp

linux/moc_SFTP.o: Generated/moc_SFTP.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/moc_SFTP.o Generated/moc_SFTP.cpp

linux/moc_SFTPThread.o: Generated/moc_SFTPThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/moc_SFTPThread.o Generated/moc_SFTPThread.cpp

linux/moc_SSHConnection.o: Generated/moc_SSHConnection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/moc_SSHConnection.o Generated/moc_SSHConnection.cpp

linux/moc_SSHWidget.o: Generated/moc_SSHWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/moc_SSHWidget.o Generated/moc_SSHWidget.cpp

linux/moc_SSHWidgetThread.o: Generated/moc_SSHWidgetThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/moc_SSHWidgetThread.o Generated/moc_SSHWidgetThread.cpp

linux/moc_Tabbinator.o: Generated/moc_Tabbinator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/moc_Tabbinator.o Generated/moc_Tabbinator.cpp

linux/moc_TransferManager.o: Generated/moc_TransferManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/moc_TransferManager.o Generated/moc_TransferManager.cpp

linux/moc_UserPreferencesDlg.o: Generated/moc_UserPreferencesDlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/moc_UserPreferencesDlg.o Generated/moc_UserPreferencesDlg.cpp

linux/qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/qrc_icons.o qrc_icons.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

